export type LegacyCanonicalTile = {
  id: number
  label: string
  url: string
  color: string
  adjacentTiles: number[]
  points: number
}

// Canonical source artifact derived from the legacy project:
// https://github.com/MatsVingerhoets/osrs-bingo/blob/main/src/data/tiles.ts
export const legacyCanonicalTiles: LegacyCanonicalTile[] = [
  {
    points: 32,
    label: 'Obtain a Ring of Endurance',
    url: '/images/001.webp',
    id: 1,
    color: 'bg-yellow-500',
    adjacentTiles: [],
  },
  {
    points: 32,
    label: 'Complete a Noxious Halberd',
    url: '/images/002.webp',
    id: 2,
    color: 'bg-yellow-500',
    adjacentTiles: [],
  },
  {
    points: 32,
    label: 'Obtain the Metamorphic Dust from CoX CM',
    url: '/images/003.webp',
    id: 3,
    color: 'bg-yellow-500',
    adjacentTiles: [],
  },
  {
    points: 32,
    label: 'Obtain all the pieces of the Voidwaker',
    url: '/images/004.webp',
    id: 4,
    color: 'bg-yellow-500',
    adjacentTiles: [],
  },
  {
    points: 32,
    label: 'Complete the full Sunfire armor set from Colosseum',
    url: '/images/005.webp',
    id: 5,
    color: 'bg-yellow-500',
    adjacentTiles: [],
  },
  {
    points: 32,
    label: 'Kill any one of the Awakened DT2 bosses',
    url: '/images/006.webp',
    id: 6,
    color: 'bg-yellow-500',
    adjacentTiles: [],
  },
  {
    points: 32,
    label: "Obtain any Boss pet that isn't from a Raid (not Chaos Elemental)",
    url: '/images/007.webp',
    id: 7,
    color: 'bg-yellow-500',
    adjacentTiles: [],
  },
  {
    points: 16,
    label:
      'Get any piece of armor from Raids (Justy, Masori, Ancestral, or Twisted Buckler)',
    url: '/images/008.webp',
    id: 8,
    color: 'bg-purple-500',
    adjacentTiles: [1, 2, 7],
  },
  {
    points: 16,
    label: "Obtain the Huntsman's Kit",
    url: '/images/009.webp',
    id: 9,
    color: 'bg-purple-500',
    adjacentTiles: [2, 3],
  },
  {
    points: 16,
    label: 'Obtain a unique from an Elite Clue Scroll reward casket',
    url: '/images/010.webp',
    id: 10,
    color: 'bg-purple-500',
    adjacentTiles: [3, 4],
  },
  {
    points: 16,
    label: 'Obtain some Dragon Limbs',
    url: '/images/011.webp',
    id: 11,
    color: 'bg-purple-500',
    adjacentTiles: [4, 5],
  },
  {
    points: 16,
    label: 'Obtain an Araxyte fang',
    url: '/images/012.webp',
    id: 12,
    color: 'bg-purple-500',
    adjacentTiles: [5, 6, 13],
  },
  {
    points: 32,
    label: 'Obtain any Raids pet',
    url: '/images/013.webp',
    id: 13,
    color: 'bg-yellow-500',
    adjacentTiles: [],
  },
  {
    points: 32,
    label: 'Obtain any Skilling pet (non-minigame)',
    url: '/images/014.webp',
    id: 14,
    color: 'bg-yellow-500',
    adjacentTiles: [],
  },
  {
    points: 16,
    label: 'Get a unique drop from Nex',
    url: '/images/015.webp',
    id: 15,
    color: 'bg-purple-500',
    adjacentTiles: [7, 14],
  },
  {
    points: 8,
    label: 'Get a Zenyte shard',
    url: '/images/016.webp',
    id: 16,
    color: 'bg-red-500',
    adjacentTiles: [8, 9, 15],
  },
  {
    points: 8,
    label: 'Get a Mimic drop',
    url: '/images/017.webp',
    id: 17,
    color: 'bg-red-500',
    adjacentTiles: [9, 10],
  },
  {
    points: 8,
    label: 'Get an Unsired',
    url: '/images/018.webp',
    id: 18,
    color: 'bg-red-500',
    adjacentTiles: [10, 11],
  },
  {
    points: 8,
    label: 'Complete the fight caves',
    url: '/images/019.webp',
    id: 19,
    color: 'bg-red-500',
    adjacentTiles: [11, 12, 20],
  },
  {
    points: 16,
    label: 'Obtain a blood shard',
    url: '/images/020.webp',
    id: 20,
    color: 'bg-purple-500',
    adjacentTiles: [13, 21],
  },
  {
    points: 32,
    label: 'Complete a full Moons of Peril set, including weapon and armour',
    url: '/images/021.webp',
    id: 21,
    color: 'bg-yellow-500',
    adjacentTiles: [],
  },
  {
    points: 32,
    label: 'Complete a full Barrows set, including weapon and armour',
    url: '/images/022.webp',
    id: 22,
    color: 'bg-yellow-500',
    adjacentTiles: [],
  },
  {
    points: 16,
    label: 'Obtain one of the Wilderness Rings',
    url: '/images/023.webp',
    id: 23,
    color: 'bg-purple-500',
    adjacentTiles: [14, 22],
  },
  {
    points: 8,
    label: 'Get any of the Ancient Statuettes or Ancient Crystal from Revs',
    url: '/images/024.webp',
    id: 24,
    color: 'bg-red-500',
    adjacentTiles: [15, 23],
  },
  {
    points: 4,
    label: 'Receive an Ancient Shard from Skotizo',
    url: '/images/025.webp',
    id: 25,
    color: 'bg-blue-300',
    adjacentTiles: [16, 17, 24],
  },
  {
    points: 4,
    label: 'Complete a Master Clue',
    url: '/images/026.webp',
    id: 26,
    color: 'bg-blue-300',
    adjacentTiles: [17, 18],
  },
  {
    points: 4,
    label: 'Obtain a pair of Dragon Boots',
    url: '/images/027.webp',
    id: 27,
    color: 'bg-blue-300',
    adjacentTiles: [18, 19, 28],
  },
  {
    points: 8,
    label: 'Obtain a Zalcano shard',
    url: '/images/028.webp',
    id: 28,
    color: 'bg-red-500',
    adjacentTiles: [20, 29],
  },
  {
    points: 16,
    label: 'Obtain an upgrade to a wilderness weapon',
    url: '/images/029.webp',
    id: 29,
    color: 'bg-purple-500',
    adjacentTiles: [21, 30],
  },
  {
    points: 32,
    label: 'Obtain a Colossal Blade',
    url: '/images/030.webp',
    id: 30,
    color: 'bg-yellow-500',
    adjacentTiles: [],
  },
  {
    points: 32,
    label: 'Obtain a mutagen from Zulrah',
    url: '/images/031.webp',
    id: 31,
    color: 'bg-yellow-500',
    adjacentTiles: [],
  },
  {
    points: 16,
    label: 'Complete a full Godsword from scratch',
    url: '/images/032.webp',
    id: 32,
    color: 'bg-purple-500',
    adjacentTiles: [22, 31],
  },
  {
    points: 8,
    label: "Get a Lightbearer or an Osmumten's Fang from ToA",
    url: '/images/033.webp',
    id: 33,
    color: 'bg-red-500',
    adjacentTiles: [23, 32],
  },
  {
    points: 4,
    label: 'Obtain an Araxyte vemon sack',
    url: '/images/034.webp',
    id: 34,
    color: 'bg-blue-300',
    adjacentTiles: [24, 33],
  },
  {
    points: 2,
    label: 'Obtain a Barrows Unique',
    url: '/images/035.webp',
    id: 35,
    color: 'bg-green-400',
    adjacentTiles: [25, 26, 34],
  },
  {
    points: 2,
    label: 'Obtain a Granite Maul',
    url: '/images/036.webp',
    id: 36,
    color: 'bg-green-400',
    adjacentTiles: [26, 27, 37],
  },
  {
    points: 4,
    label: 'Obtain a Malediction Shard',
    url: '/images/037.webp',
    id: 37,
    color: 'bg-blue-300',
    adjacentTiles: [28, 38],
  },
  {
    points: 8,
    label: 'Get an Avernic Hilt drop from ToB',
    url: '/images/038.webp',
    id: 38,
    color: 'bg-red-500',
    adjacentTiles: [29, 39],
  },
  {
    points: 16,
    label: 'Obtain any piece of the Soulreaper Axe',
    url: '/images/039.webp',
    id: 39,
    color: 'bg-purple-500',
    adjacentTiles: [30, 40],
  },
  {
    points: 32,
    label: 'Obtain any Jar',
    url: '/images/040.webp',
    id: 40,
    color: 'bg-yellow-500',
    adjacentTiles: [],
  },
  {
    points: 32,
    label: 'Obtain any of the Remnants from ToA',
    url: '/images/041.webp',
    id: 41,
    color: 'bg-yellow-500',
    adjacentTiles: [],
  },
  {
    points: 16,
    label: "Get a Dizana's Quiver (First quiver gets double points)",
    url: '/images/042.webp',
    id: 42,
    color: 'bg-purple-500',
    adjacentTiles: [31, 41],
  },
  {
    points: 8,
    label: 'Obtain the Crystal Tool Seed',
    url: '/images/043.webp',
    id: 43,
    color: 'bg-red-500',
    adjacentTiles: [32, 42],
  },
  {
    points: 4,
    label: 'Obtain any Tempoross unique',
    url: '/images/044.webp',
    id: 44,
    color: 'bg-blue-300',
    adjacentTiles: [33, 43],
  },
  {
    points: 2,
    label: "Obtain any piece of the Angler's Outfit",
    url: '/images/045.webp',
    id: 45,
    color: 'bg-green-400',
    adjacentTiles: [34, 44],
  },
  {
    points: 1,
    label: "Get a Vorkath's Head",
    url: '/images/046.webp',
    id: 46,
    color: 'bg-white',
    adjacentTiles: [35, 36, 45, 47],
  },
  {
    points: 2,
    label: "Purchase Kovac's Grog",
    url: '/images/047.webp',
    id: 47,
    color: 'bg-green-400',
    adjacentTiles: [37, 48],
  },
  {
    points: 4,
    label: 'Receive a Penance Item from Barbarian Assault',
    url: '/images/048.webp',
    id: 48,
    color: 'bg-blue-300',
    adjacentTiles: [38, 49],
  },
  {
    points: 8,
    label: 'Get any weapon from God Wars Dungeon',
    url: '/images/049.webp',
    id: 49,
    color: 'bg-red-500',
    adjacentTiles: [39, 50],
  },
  {
    points: 16,
    label: 'Kill TzKal-Zuk (First cape gets double points)',
    url: '/images/050.webp',
    id: 50,
    color: 'bg-purple-500',
    adjacentTiles: [40, 51],
  },
  {
    points: 32,
    label: 'Obtain the Cursed Phalanx from ToA',
    url: '/images/051.webp',
    id: 51,
    color: 'bg-yellow-500',
    adjacentTiles: [],
  },
  {
    points: 32,
    label:
      "Obtain a wilderness weapon (craws bow, thammaron's sceptre, viggora's chainmace)",
    url: '/images/052.webp',
    id: 52,
    color: 'bg-yellow-500',
    adjacentTiles: [],
  },
  {
    points: 16,
    label: 'Obtain a Hydra Leather from the Alchemical Hydra',
    url: '/images/053.webp',
    id: 53,
    color: 'bg-purple-500',
    adjacentTiles: [41, 52, 64],
  },
  {
    points: 8,
    label: 'Obtain the crystal weapon seed or the crystal armour seed',
    url: '/images/054.webp',
    id: 54,
    color: 'bg-red-500',
    adjacentTiles: [42, 53, 65],
  },
  {
    points: 4,
    label: "Obtain a Scurrius' Spine",
    url: '/images/055.webp',
    id: 55,
    color: 'bg-blue-300',
    adjacentTiles: [43, 54, 66],
  },
  {
    points: 2,
    label: 'Obtain a Kraken Testicle',
    url: '/images/056.webp',
    id: 56,
    color: 'bg-green-400',
    adjacentTiles: [44, 55, 67],
  },
  {
    points: 1,
    label: 'Get any unique drop from the Phantom Muspah',
    url: '/images/057.webp',
    id: 57,
    color: 'bg-white',
    adjacentTiles: [45, 56, 68, 69],
  },
  {
    points: 1,
    label: 'Get any unique drop from Zulrah',
    url: '/images/058.webp',
    id: 58,
    color: 'bg-white',
    adjacentTiles: [47, 59, 69, 70],
  },
  {
    points: 2,
    label: 'Obtain an Abyssal Whip drop',
    url: '/images/059.webp',
    id: 59,
    color: 'bg-green-400',
    adjacentTiles: [48, 60, 71],
  },
  {
    points: 4,
    label: 'Obtain a Sarachnis Cudgel',
    url: '/images/060.webp',
    id: 60,
    color: 'bg-blue-300',
    adjacentTiles: [49, 61, 72],
  },
  {
    points: 8,
    label: 'Obtain Granite Gloves, Ring, or Hammer from Grotesque Guardians',
    url: '/images/061.webp',
    id: 61,
    color: 'bg-red-500',
    adjacentTiles: [50, 62, 73],
  },
  {
    points: 16,
    label: 'Obtain a Masori Crafting Kit from ToA',
    url: '/images/062.webp',
    id: 62,
    color: 'bg-purple-500',
    adjacentTiles: [51, 63, 74],
  },
  {
    points: 32,
    label:
      'Obtain a nightmare staff and an associated orb (harmonized, volatile, or eldritch)',
    url: '/images/063.webp',
    id: 63,
    color: 'bg-yellow-500',
    adjacentTiles: [],
  },
  {
    points: 32,
    label: 'Get a Fox Whistle from Forestry',
    url: '/images/064.webp',
    id: 64,
    color: 'bg-yellow-500',
    adjacentTiles: [],
  },
  {
    points: 16,
    label: 'Obtain a Broken Dragon Pickaxe from Volcanic Mine',
    url: '/images/065.webp',
    id: 65,
    color: 'bg-purple-500',
    adjacentTiles: [64, 75],
  },
  {
    points: 8,
    label: 'Get any piece of armor from God Wars Dungeon',
    url: '/images/066.webp',
    id: 66,
    color: 'bg-red-500',
    adjacentTiles: [65, 76],
  },
  {
    points: 4,
    label: 'Obtain an Odium Shard',
    url: '/images/067.webp',
    id: 67,
    color: 'bg-blue-300',
    adjacentTiles: [66, 77],
  },
  {
    points: 2,
    label: 'Obtain any DKS Ring',
    url: '/images/068.webp',
    id: 68,
    color: 'bg-green-400',
    adjacentTiles: [67, 78, 79],
  },
  {
    points: 2,
    label: 'Obtain a Unique from any Clue Tier',
    url: '/images/069.webp',
    id: 69,
    color: 'bg-green-400',
    adjacentTiles: [79, 80],
  },
  {
    points: 2,
    label: 'Obtain a unique from Moons of Peril',
    url: '/images/070.webp',
    id: 70,
    color: 'bg-green-400',
    adjacentTiles: [71, 80, 81],
  },
  {
    points: 4,
    label: 'Complete 3 Hard Clues',
    url: '/images/071.webp',
    id: 71,
    color: 'bg-blue-300',
    adjacentTiles: [72, 82],
  },
  {
    points: 8,
    label: 'Get a unique from the Colosseum',
    url: '/images/072.webp',
    id: 72,
    color: 'bg-red-500',
    adjacentTiles: [73, 83],
  },
  {
    points: 16,
    label: "Obtain the Pharoah's Sceptre",
    url: '/images/073.webp',
    id: 73,
    color: 'bg-purple-500',
    adjacentTiles: [74, 84],
  },
  {
    points: 32,
    label: 'Create an Abyssal Bludgeon from scratch',
    url: '/images/074.webp',
    id: 74,
    color: 'bg-yellow-500',
    adjacentTiles: [],
  },
  {
    points: 32,
    label: 'Complete a full Crystal Armor Set',
    url: '/images/075.webp',
    id: 75,
    color: 'bg-yellow-500',
    adjacentTiles: [],
  },
  {
    points: 16,
    label: 'Get any ornament kit from a Clue Scroll',
    url: '/images/076.webp',
    id: 76,
    color: 'bg-purple-500',
    adjacentTiles: [75, 85],
  },
  {
    points: 8,
    label: 'Get an Awakened Orb',
    url: '/images/077.webp',
    id: 77,
    color: 'bg-red-500',
    adjacentTiles: [76, 86],
  },
  {
    points: 4,
    label: 'Obtain any of the quartz from the DT2 bosses',
    url: '/images/078.webp',
    id: 78,
    color: 'bg-blue-300',
    adjacentTiles: [77, 87, 88],
  },
  {
    points: 4,
    label: 'Receive a Reward from Soul Wars Crate',
    url: '/images/079.webp',
    id: 79,
    color: 'bg-blue-300',
    adjacentTiles: [88, 89],
  },
  {
    points: 4,
    label: 'Obtain any Wintertodt unique',
    url: '/images/080.webp',
    id: 80,
    color: 'bg-blue-300',
    adjacentTiles: [89, 90],
  },
  {
    points: 4,
    label: 'Obtain a Fedora',
    url: '/images/081.webp',
    id: 81,
    color: 'bg-blue-300',
    adjacentTiles: [90, 91],
  },
  {
    points: 8,
    label: 'Get a piece of the Voidwaker',
    url: '/images/082.webp',
    id: 82,
    color: 'bg-red-500',
    adjacentTiles: [83, 92],
  },
  {
    points: 16,
    label: 'Obtain a unique from a Master Clue Scroll casket',
    url: '/images/083.webp',
    id: 83,
    color: 'bg-purple-500',
    adjacentTiles: [84, 93],
  },
  {
    points: 32,
    label: 'Obtain an Abyssal Lantern',
    url: '/images/084.webp',
    id: 84,
    color: 'bg-yellow-500',
    adjacentTiles: [],
  },
  {
    points: 32,
    label: 'Obtain a mega-rare weapon from Raids (Shadow, Scythe, TBow)',
    url: '/images/085.webp',
    id: 85,
    color: 'bg-yellow-500',
    adjacentTiles: [],
  },
  {
    points: 16,
    label: 'Complete an Odium Ward or a Malediction Ward',
    url: '/images/086.webp',
    id: 86,
    color: 'bg-purple-500',
    adjacentTiles: [85, 94],
  },
  {
    points: 8,
    label: 'Obtain any crystal from Cerberus',
    url: '/images/087.webp',
    id: 87,
    color: 'bg-red-500',
    adjacentTiles: [86, 95, 96],
  },
  {
    points: 8,
    label: 'Obtain the Tome of Fire or the Tome of Water',
    url: '/images/088.webp',
    id: 88,
    color: 'bg-red-500',
    adjacentTiles: [96, 97],
  },
  {
    points: 8,
    label: 'Get a Prayer Scroll from CoX',
    url: '/images/089.webp',
    id: 89,
    color: 'bg-red-500',
    adjacentTiles: [97, 98],
  },
  {
    points: 8,
    label: 'Get a unique from a Hard Clue Scroll',
    url: '/images/090.webp',
    id: 90,
    color: 'bg-red-500',
    adjacentTiles: [98, 99],
  },
  {
    points: 8,
    label: 'Get a Tormented Synapse',
    url: '/images/091.webp',
    id: 91,
    color: 'bg-red-500',
    adjacentTiles: [92, 99, 100],
  },
  {
    points: 16,
    label: "Obtain a piece of the Dagon'hai robes set",
    url: '/images/092.webp',
    id: 92,
    color: 'bg-purple-500',
    adjacentTiles: [93, 101],
  },
  {
    points: 32,
    label: 'Obtain a Dragon Warhammer',
    url: '/images/093.webp',
    id: 93,
    color: 'bg-yellow-500',
    adjacentTiles: [],
  },
  {
    points: 32,
    label: 'Obtain a unique from a Clue Mega-Rare Table',
    url: '/images/094.webp',
    id: 94,
    color: 'bg-yellow-500',
    adjacentTiles: [],
  },
  {
    points: 16,
    label: 'Get any weapon from Raids',
    url: '/images/095.webp',
    id: 95,
    color: 'bg-purple-500',
    adjacentTiles: [94, 102, 103],
  },
  {
    points: 16,
    label: "Obtain a Hydra's Claw",
    url: '/images/096.webp',
    id: 96,
    color: 'bg-purple-500',
    adjacentTiles: [103, 104],
  },
  {
    points: 16,
    label: 'Get a piece of the Virtus armor set from any of the DT2 bosses',
    url: '/images/097.webp',
    id: 97,
    color: 'bg-purple-500',
    adjacentTiles: [104, 105],
  },
  {
    points: 16,
    label: 'Get a vestige from any of the DT2 bosses',
    url: '/images/098.webp',
    id: 98,
    color: 'bg-purple-500',
    adjacentTiles: [105, 106],
  },
  {
    points: 16,
    label: 'Get an enhanced crystal weapon seed',
    url: '/images/099.webp',
    id: 99,
    color: 'bg-purple-500',
    adjacentTiles: [106, 107],
  },
  {
    points: 16,
    label: 'Get a unique drop from the Nightmare',
    url: '/images/100.webp',
    id: 100,
    color: 'bg-purple-500',
    adjacentTiles: [101, 107, 108],
  },
  {
    points: 32,
    label: 'Obtain any sigil from the Corporeal Beast',
    url: '/images/101.webp',
    id: 101,
    color: 'bg-yellow-500',
    adjacentTiles: [],
  },
  {
    points: 32,
    label: 'Craft a full set of Hueycoatl Hide Armour from scratch',
    url: '/images/102.webp',
    id: 102,
    color: 'bg-yellow-500',
    adjacentTiles: [],
  },
  {
    points: 32,
    label: 'Obtain a Twisted Kit from CoX CM',
    url: '/images/103.webp',
    id: 103,
    color: 'bg-yellow-500',
    adjacentTiles: [],
  },
  {
    points: 32,
    label: 'Obtain a Draconic, Wyvern, or Skeletal Visage',
    url: '/images/104.webp',
    id: 104,
    color: 'bg-yellow-500',
    adjacentTiles: [],
  },
  {
    points: 32,
    label: 'Obtain the Golden Tench from Aerial Fishing',
    url: '/images/105.webp',
    id: 105,
    color: 'bg-yellow-500',
    adjacentTiles: [],
  },
  {
    points: 32,
    label: 'Obtain an Eternal Gem or Imbued Heart',
    url: '/images/106.webp',
    id: 106,
    color: 'bg-yellow-500',
    adjacentTiles: [],
  },
  {
    points: 32,
    label: 'Obtain all of the Wilderness Rings',
    url: '/images/107.webp',
    id: 107,
    color: 'bg-yellow-500',
    adjacentTiles: [],
  },
  {
    points: 32,
    label: 'Obtain Smolcano, Phoenix, Tiny Tempor, or the Abyssal Protector',
    url: '/images/108.webp',
    id: 108,
    color: 'bg-yellow-500',
    adjacentTiles: [],
  },
]
